/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SignalStatus = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const TrafficSignalView = IDL.Record({
  'id' : IDL.Nat,
  'status' : SignalStatus,
  'lastUpdated' : IDL.Int,
  'location' : IDL.Text,
});
export const Urgency = IDL.Variant({
  'normal' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
});
export const EmergencyMessageView = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'acknowledgedAt' : IDL.Opt(IDL.Int),
  'urgency' : Urgency,
  'dispatched' : IDL.Bool,
  'dispatchedAt' : IDL.Opt(IDL.Int),
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'response' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'respondedAt' : IDL.Opt(IDL.Int),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'acknowledgeEmergencyMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'dispatchEmergencyMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getSignal' : IDL.Func([IDL.Nat], [IDL.Opt(TrafficSignalView)], ['query']),
  'listEmergencyMessages' : IDL.Func(
      [],
      [IDL.Vec(EmergencyMessageView)],
      ['query'],
    ),
  'listSignals' : IDL.Func([], [IDL.Vec(TrafficSignalView)], ['query']),
  'resolveEmergencyMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'respondToEmergencyMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'submitEmergencyMessage' : IDL.Func(
      [IDL.Text, Urgency, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'unresolvedEmergencyCount' : IDL.Func([], [IDL.Nat], ['query']),
  'updateSignalStatus' : IDL.Func([IDL.Nat, SignalStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SignalStatus = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const TrafficSignalView = IDL.Record({
    'id' : IDL.Nat,
    'status' : SignalStatus,
    'lastUpdated' : IDL.Int,
    'location' : IDL.Text,
  });
  const Urgency = IDL.Variant({
    'normal' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
  });
  const EmergencyMessageView = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'acknowledgedAt' : IDL.Opt(IDL.Int),
    'urgency' : Urgency,
    'dispatched' : IDL.Bool,
    'dispatchedAt' : IDL.Opt(IDL.Int),
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'response' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'respondedAt' : IDL.Opt(IDL.Int),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'acknowledgeEmergencyMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'dispatchEmergencyMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getSignal' : IDL.Func([IDL.Nat], [IDL.Opt(TrafficSignalView)], ['query']),
    'listEmergencyMessages' : IDL.Func(
        [],
        [IDL.Vec(EmergencyMessageView)],
        ['query'],
      ),
    'listSignals' : IDL.Func([], [IDL.Vec(TrafficSignalView)], ['query']),
    'resolveEmergencyMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'respondToEmergencyMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'submitEmergencyMessage' : IDL.Func(
        [IDL.Text, Urgency, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'unresolvedEmergencyCount' : IDL.Func([], [IDL.Nat], ['query']),
    'updateSignalStatus' : IDL.Func([IDL.Nat, SignalStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };