/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmergencyMessageView {
  'id' : bigint,
  'resolved' : boolean,
  'acknowledgedAt' : [] | [bigint],
  'urgency' : Urgency,
  'dispatched' : boolean,
  'dispatchedAt' : [] | [bigint],
  'acknowledged' : boolean,
  'message' : string,
  'response' : [] | [string],
  'timestamp' : bigint,
  'respondedAt' : [] | [bigint],
  'location' : string,
}
export type SignalStatus = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface TrafficSignalView {
  'id' : bigint,
  'status' : SignalStatus,
  'lastUpdated' : bigint,
  'location' : string,
}
export type Urgency = { 'normal' : null } |
  { 'high' : null } |
  { 'critical' : null };
export interface _SERVICE {
  'acknowledgeEmergencyMessage' : ActorMethod<[bigint], boolean>,
  'dispatchEmergencyMessage' : ActorMethod<[bigint], boolean>,
  'getSignal' : ActorMethod<[bigint], [] | [TrafficSignalView]>,
  'listEmergencyMessages' : ActorMethod<[], Array<EmergencyMessageView>>,
  'listSignals' : ActorMethod<[], Array<TrafficSignalView>>,
  'resolveEmergencyMessage' : ActorMethod<[bigint], boolean>,
  'respondToEmergencyMessage' : ActorMethod<[bigint, string], boolean>,
  'submitEmergencyMessage' : ActorMethod<[string, Urgency, string], bigint>,
  'unresolvedEmergencyCount' : ActorMethod<[], bigint>,
  'updateSignalStatus' : ActorMethod<[bigint, SignalStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];