/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrafficSignalView {
    id: bigint;
    status: SignalStatus;
    lastUpdated: bigint;
    location: string;
}
export interface EmergencyMessageView {
    id: bigint;
    resolved: boolean;
    acknowledgedAt?: bigint;
    urgency: Urgency;
    dispatched: boolean;
    dispatchedAt?: bigint;
    acknowledged: boolean;
    message: string;
    response?: string;
    timestamp: bigint;
    respondedAt?: bigint;
    location: string;
}
export enum SignalStatus {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export enum Urgency {
    normal = "normal",
    high = "high",
    critical = "critical"
}
export interface backendInterface {
    acknowledgeEmergencyMessage(id: bigint): Promise<boolean>;
    dispatchEmergencyMessage(id: bigint): Promise<boolean>;
    getSignal(id: bigint): Promise<TrafficSignalView | null>;
    listEmergencyMessages(): Promise<Array<EmergencyMessageView>>;
    listSignals(): Promise<Array<TrafficSignalView>>;
    resolveEmergencyMessage(id: bigint): Promise<boolean>;
    respondToEmergencyMessage(id: bigint, response: string): Promise<boolean>;
    submitEmergencyMessage(message: string, urgency: Urgency, location: string): Promise<bigint>;
    unresolvedEmergencyCount(): Promise<bigint>;
    updateSignalStatus(id: bigint, status: SignalStatus): Promise<boolean>;
}
import type { EmergencyMessageView as _EmergencyMessageView, SignalStatus as _SignalStatus, TrafficSignalView as _TrafficSignalView, Urgency as _Urgency } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeEmergencyMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeEmergencyMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeEmergencyMessage(arg0);
            return result;
        }
    }
    async dispatchEmergencyMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dispatchEmergencyMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dispatchEmergencyMessage(arg0);
            return result;
        }
    }
    async getSignal(arg0: bigint): Promise<TrafficSignalView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignal(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignal(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEmergencyMessages(): Promise<Array<EmergencyMessageView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmergencyMessages();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmergencyMessages();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSignals(): Promise<Array<TrafficSignalView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSignals();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSignals();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveEmergencyMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveEmergencyMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveEmergencyMessage(arg0);
            return result;
        }
    }
    async respondToEmergencyMessage(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToEmergencyMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToEmergencyMessage(arg0, arg1);
            return result;
        }
    }
    async submitEmergencyMessage(arg0: string, arg1: Urgency, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEmergencyMessage(arg0, to_candid_Urgency_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEmergencyMessage(arg0, to_candid_Urgency_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async unresolvedEmergencyCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.unresolvedEmergencyCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unresolvedEmergencyCount();
            return result;
        }
    }
    async updateSignalStatus(arg0: bigint, arg1: SignalStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignalStatus(arg0, to_candid_SignalStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignalStatus(arg0, to_candid_SignalStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EmergencyMessageView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyMessageView): EmergencyMessageView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SignalStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalStatus): SignalStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficSignalView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficSignalView): TrafficSignalView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Urgency_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Urgency): Urgency {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrafficSignalView]): TrafficSignalView | null {
    return value.length === 0 ? null : from_candid_TrafficSignalView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SignalStatus;
    lastUpdated: bigint;
    location: string;
}): {
    id: bigint;
    status: SignalStatus;
    lastUpdated: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_SignalStatus_n4(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        location: value.location
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    resolved: boolean;
    acknowledgedAt: [] | [bigint];
    urgency: _Urgency;
    dispatched: boolean;
    dispatchedAt: [] | [bigint];
    acknowledged: boolean;
    message: string;
    response: [] | [string];
    timestamp: bigint;
    respondedAt: [] | [bigint];
    location: string;
}): {
    id: bigint;
    resolved: boolean;
    acknowledgedAt?: bigint;
    urgency: Urgency;
    dispatched: boolean;
    dispatchedAt?: bigint;
    acknowledged: boolean;
    message: string;
    response?: string;
    timestamp: bigint;
    respondedAt?: bigint;
    location: string;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        acknowledgedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.acknowledgedAt)),
        urgency: from_candid_Urgency_n10(_uploadFile, _downloadFile, value.urgency),
        dispatched: value.dispatched,
        dispatchedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.dispatchedAt)),
        acknowledged: value.acknowledged,
        message: value.message,
        response: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.response)),
        timestamp: value.timestamp,
        respondedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.respondedAt)),
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    high: null;
} | {
    critical: null;
}): Urgency {
    return "normal" in value ? Urgency.normal : "high" in value ? Urgency.high : "critical" in value ? Urgency.critical : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): SignalStatus {
    return "red" in value ? SignalStatus.red : "green" in value ? SignalStatus.green : "yellow" in value ? SignalStatus.yellow : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrafficSignalView>): Array<TrafficSignalView> {
    return value.map((x)=>from_candid_TrafficSignalView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmergencyMessageView>): Array<EmergencyMessageView> {
    return value.map((x)=>from_candid_EmergencyMessageView_n7(_uploadFile, _downloadFile, x));
}
function to_candid_SignalStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStatus): _SignalStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Urgency_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Urgency): _Urgency {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Urgency): {
    normal: null;
} | {
    high: null;
} | {
    critical: null;
} {
    return value == Urgency.normal ? {
        normal: null
    } : value == Urgency.high ? {
        high: null
    } : value == Urgency.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStatus): {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == SignalStatus.red ? {
        red: null
    } : value == SignalStatus.green ? {
        green: null
    } : value == SignalStatus.yellow ? {
        yellow: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
